theme: jekyll-theme-minimal

# Site wide configuration

title: *Personal Website* >
George Shi
locale: en_US
logo: asset/img/road.jpg
# Author Settings
author: George Shi # add your name
author-img: image/bio-photo.jpg # add your photo
about-author: I am a digital health marketer and data scientist # add description
social-github: georgeshi-hub # add your Github handle
social-linkedin: georgeshi # add your Linkedin handle
social-email: george.shi@outlook.com # add your Email address
